
class MessageIndex():
	prqaMessage = {
		9:"The length of this preprocessed source code line has exceeded the size of an internal buffer. ",
		40:"Definition of size_t differs from configured type. ",
		41:"Definition of ptrdiff_t differs from configured type. ",
		42:"Definition of wchar_t differs from configured type. ",
		97:"Recoverable dataflow problem. Analysis continues. Please inform Programming Research. ",
		159:"The maximum number of errors set by -maxerr has been exceeded - the analysis has been aborted. Incor",
		160:"[U] Using unsupported conversion specifier number %s. ",
		161:"[U] Unknown flags used with 'i' or 'd' conversion specifier, number %s. ",
		162:"[U] Unknown flags used with 'o' conversion specifier, number %s. ",
		163:"[U] Unknown flags used with 'u' conversion specifier, number %s. ",
		164:"[U] Unknown flags used with 'x' conversion specifier, number %s. ",
		165:"[U] Unknown flags used with 'X' conversion specifier, number %s. ",
		166:"[U] Unknown flags used with 'f' conversion specifier, number %s. ",
		167:"[U] Unknown flags used with 'e' conversion specifier, number %s. ",
		168:"[U] Unknown flags used with 'E' conversion specifier, number %s. ",
		169:"[U] Unknown flags used with 'g' conversion specifier, number %s. ",
		170:"[U] Unknown flags used with 'G' conversion specifier, number %s. ",
		171:"[U] Unknown flags used with 'c' conversion specifier, number %s. ",
		172:"[U] Unknown flags used with '%%' conversion specifier, number %s. ",
		173:"[U] Unknown flags used with 's' conversion specifier, number %s. ",
		174:"[U] Unknown flags used with 'n' conversion specifier, number %s. ",
		175:"[U] Unknown flags used with 'p' conversion specifier, number %s. ",
		176:"[U] Unknown conversion specifier, number %s. ",
		177:"[U] Field width exceeds 509 characters. ",
		178:"[U] Precision width exceeds 509 characters. ",
		179:"[U] Argument type does not match conversion specifier number %s. ",
		180:"[C99] Use of ll for conversion specifier. ",
		184:"[U] Insufficient arguments to satisfy conversion specifier, number %s. ",
		185:"[U] Call contains more arguments than conversion specifiers. ",
		186:"[U] Call must contain at least one argument. ",
		190:"[U] Using unsupported conversion specifier number %s. ",
		191:"[U] Unknown flags used with 'd/i/n' conversion specifier, number %s. ",
		192:"[U] Unknown flags used with 'o' conversion specifier, number %s. ",
		193:"[U] Unknown flags used with 'u' conversion specifier, number %s. ",
		194:"[U] Unknown flags used with 'x/X' conversion specifier, number %s. ",
		195:"[U] Unknown flags used with 'e/E/f/g/G' conversion specifier, number %s. ",
		196:"[U] Unknown flags used with 's' conversion specifier, number %s. ",
		197:"[U] Unknown flags used with 'p' conversion specifier, number %s. ",
		198:"[U] Unknown flags used with '%%' conversion specifier, number %s. ",
		199:"[U] Unknown flags used with '[' conversion specifier, number %s. ",
		200:"[U] Unknown flags used with 'c' conversion specifier, number %s. ",
		201:"[U] Unknown conversion specifier, number %s. ",
		202:"[I] '-' character in '[]' conversion specification is implementation defined. ",
		203:"[U] Value of character prior to '-' in '[]' is greater than following character. ",
		204:"[U] Field width exceeds 509 characters. ",
		206:"[U] Argument type does not match conversion specifier number %s. ",
		207:"[U] 'scanf' expects address of objects being stored into. ",
		208:"[U] Same character occurs in scanset more than once. ",
		231:"[S] Hex escape sequence must have at least one hex digit. ",
		232:"[C] Escape sequence value must be in the representable range for 'unsigned char'. ",
		233:"[C] Octal escape sequence value must be in the representable range for 'unsigned char'. ",
		234:"[S] Hex escape sequence must have at least one hex digit. ",
		235:"[U] Unknown escape sequence. ",
		240:"[E] This file contains the control-M character at the end of a line. ",
		241:"[E] This file contains the control-Z character - was this transferred from a PC? ",
		244:"[C] Value of character constant is not representable as 'int'. ",
		245:"[S] Empty character constant. ",
		246:"[E] Binary integer constants are a language extension. ",
		249:"[S] Character constant contains new-line character. ",
		250:"[S] Character constant contains new-line character. Backslash is used to define an escape sequence. ",
		251:"[S] Character constant contains new-line character. The trigraph '??/' is replaced by '\\'. Backslas",
		257:"[S] String literal is not terminated. A trigraph has been used in the construction of an escape sequ",
		258:"[S] String literal is not terminated. A backslash character has been used to define an escape sequen",
		259:"[S] String literal is not terminated. ",
		261:"[C] Comment still open at end of included file. ",
		268:"[S] Comment open at end of translation unit. ",
		269:"[S] Unexpected end of file. ",
		271:"[I] Result of << on value of constant signed expression is implementation defined. ",
		272:"[I] Value of integer expression is apparently not representable in the signed result type. ",
		273:"[I] Value of integer expression is definitely not representable in the signed result type. ",
		274:"[I] Value of integer constant expression is not representable in the signed result type. ",
		275:"[U] Floating value is out of range for conversion to destination type. ",
		277:"[I] An integer constant expression with negative value is being converted to an unsigned type. ",
		278:"[C] Value of constant signed expression is unrepresentable. ",
		280:"Value of integer constant expression may not be representable in the signed result type. ",
		281:"Value of integer expression may not always be representable in the signed result type. ",
		282:"Value of integer expression may apparently not always be representable in the signed result type. ",
		284:"[I] Multiple character constants have implementation defined values. ",
		285:"[I] Character is not a member of the basic source character set. ",
		286:"[I] String literal contains character which is not a member of the basic source character set. ",
		287:"[I] Header name contains character which is not a member of the basic source character set. ",
		288:"[I] Source file '%s' has comments containing characters which are not members of the basic source ch",
		289:"[I] Source file '%s' has preprocessing tokens containing characters which are not members of the bas",
		290:"An integer expression with a value that is definitely negative is being converted to an unsigned typ",
		291:"An integer expression with a value that is apparently negative is being converted to an unsigned typ",
		292:"[I] Source file '%s' has comments containing characters which are not members of the basic source ch",
		294:"[I] Result of << on value of signed expression is definitely implementation defined. ",
		295:"[I] Result of << on value of signed expression is apparently implementation defined. ",
		296:"[U] Value of signed expression is definitely not representable. ",
		297:"[U] Value of signed expression is apparently not representable. ",
		299:"[I] Source file '%s' includes #pragma directives containing characters which are not members of the ",
		301:"[u] Cast between a pointer to object and a floating type. ",
		302:"[u] Cast between a pointer to function and a floating type. ",
		303:"[I] Cast between a pointer to volatile object and an integral type. ",
		304:"[U] The address of an array declared 'register' may not be computed. ",
		305:"[I] Cast between a pointer to function and an integral type. ",
		306:"[I] Cast between a pointer to object and an integral type. ",
		307:"[u] Cast between a pointer to object and a pointer to function. ",
		308:"Non-portable cast involving pointer to an incomplete type. ",
		309:"[U] Integral type is not large enough to hold a pointer value. ",
		310:"Casting to different object pointer type. ",
		311:"Dangerous pointer cast results in loss of const qualification. ",
		312:"Dangerous pointer cast results in loss of volatile qualification. ",
		313:"Casting to different function pointer type. ",
		320:"[C99] Declaration within 'for' statement. ",
		321:"[C] Declaration within 'for' statement defines an identifier '%s' which is not an object. ",
		322:"[C] Illegal storage class specifier used in 'for' statement declaration. ",
		336:"Macro defined as an octal constant. ",
		337:"[U] String literal has undefined value. This may be a result of using '#' on \\. ",
		338:"[C] Octal or hex escape sequence value is too large for 'unsigned char' or 'wchar_t' type. ",
		339:"Octal constant used. ",
		340:"Many K&R compilers will not accept '#error'. ",
		341:"K&R compilers do not support the ISO stringify operator '#'. ",
		342:"K&R compilers do not support the ISO glue operator '##'. ",
		343:"String concatenation is an ISO feature that may not work on K&R compilers. ",
		344:"K&R compilers do not support function prototypes. ",
		345:"Primitive K&R compilers will treat 'void' as an identifier. ",
		346:"'%s' is an ISO keyword and will not be recognized by K&R compilers. ",
		347:"K&R compilers do not allow initialization of 'extern' variables. ",
		348:"Primitive K&R compilers do not support bit-fields. ",
		349:"Unary '+' is an ISO feature that is not supported by all K&R compilers. ",
		350:"Some K&R compilers do not support 'enum', or do not support it correctly. ",
		351:"Locally declared aggregates and arrays cannot be initialized in K&R. ",
		352:"'#elif' is not supported by all K&R compilers. ",
		371:"[L] Nesting levels of blocks exceeds 127 - program does not conform strictly to ISO:C99. ",
		372:"[L] Nesting levels of conditional inclusion exceeds 63 - program does not conform strictly to ISO:C9",
		375:"[L] Nesting of parenthesized expressions exceeds 63 - program does not conform strictly to ISO:C99. ",
		380:"[L] Number of macro definitions exceeds 4095 - program does not conform strictly to ISO:C99. ",
		388:"[L] '#include '%s' causes nesting to exceed 15 levels - program does not conform strictly to ISO:C9",
		390:"[L] Number of members in 'struct' or 'union' exceeds 1023 - program does not conform strictly to ISO",
		391:"[L] Number of enumeration constants exceeds 1023 - program does not conform strictly to ISO:C99. ",
		392:"[L] Nesting of 'struct' or 'union' types exceeds 63 - program does not conform strictly to ISO:C99. ",
		400:"[U] '%s' is modified more than once between sequence points - evaluation order undefined. ",
		401:"[U] '%s' may be modified more than once between sequence points - evaluation order undefined. ",
		402:"[U] '%s' is modified and accessed between sequence points - evaluation order undefined. ",
		403:"[U] '%s' may be modified and accessed between sequence points - evaluation order undefined. ",
		410:"[L] Nesting of parentheses exceeds 32 - program does not conform strictly to ISO:C90. ",
		422:"[C] Function call contains fewer arguments than prototype specifies. ",
		423:"[C] Function call contains more arguments than prototype specifies. ",
		426:"[C] Called function has incomplete return type. ",
		427:"[C] Function or pointer to function required in function call expression. ",
		428:"Function identifier is not followed by () but a function call may be intended. ",
		429:"[C] Argument is not of arithmetic type. ",
		430:"[C] Argument is not a compatible 'struct' / 'union' type. ",
		431:"[C] Pointer argument has differently qualified base type. ",
		432:"[C] Argument is not a compatible pointer type. ",
		434:"[C] '%s' is not declared. ",
		435:"[C] Unknown member '%s'. ",
		436:"[C] Left operand of '.' must be a 'struct' or 'union' type. ",
		437:"[C] Left operand of '->' must be a pointer to a 'struct' or 'union' type. ",
		446:"[C] Operand of ++/-- must have scalar (arithmetic or pointer) type. ",
		447:"[C] Operand of ++/-- must be a modifiable object. ",
		448:"[C] Cannot increment (decrement) a pointer to an object of unknown size. ",
		449:"[C] Cannot increment (decrement) a pointer to a function. ",
		450:"[C] Array cannot be converted to pointer type because it is not an lvalue. Context requires a pointe",
		451:"[C] Subscripting requires a pointer (or array lvalue). ",
		452:"[C] Cannot subscript a pointer to an object of unknown size. ",
		453:"[C] Subscript must have integral type. ",
		454:"[C] The address-of operator '&' cannot be applied to an object declared with 'register'. ",
		456:"[C] This object does not have an address - '&' may only be applied to lvalues. ",
		457:"[C] The address-of operator '&' cannot be applied to a bit-field. ",
		458:"[C] Pointer required for dereferencing operation '[]', '*' or '->'. ",
		466:"[C] Unary '+' requires arithmetic operand. ",
		467:"[C] Logical not '!' requires scalar (arithmetic or pointer) operand. ",
		468:"[C] Unary '-' requires arithmetic operand. ",
		469:"[C] Bitwise not '~' requires integral operand. ",
		473:"[C] Result of 'sizeof' will not fit 'size_t' type. ",
		475:"[u] Bit-field expression has undefined size. ",
		476:"[C] 'sizeof' cannot be applied to a bit-field. ",
		477:"[C] 'sizeof' cannot be applied to a function. ",
		478:"[C] 'sizeof' cannot be applied to an object of unknown size. ",
		481:"[C] Only scalar expressions may be cast to other types. ",
		482:"[C] Expressions may only be cast to scalar types. ",
		483:"[C] A pointer to an object of unknown size cannot be the operand of an addition operation. ",
		484:"[C] A pointer to an object of unknown size cannot be the left operand of an subtraction operation. ",
		485:"[C] Only integral expressions may be added to pointers. ",
		486:"[C] Only integral expressions and compatible pointers may be subtracted from pointers. ",
		487:"[C] Only pointers to compatible object types may be subtracted from each other. ",
		488:"Performing pointer arithmetic. ",
		489:"Increment or decrement operation performed on pointer. ",
		490:"Relational operator applied to a pointer. ",
		493:"[C] Left operand must have arithmetic type. ",
		494:"[C] Right operand must have arithmetic type. ",
		495:"[C] Left operand of '%', '<<', '>>', '&', '^' or '|' must have integral type. ",
		496:"[C] Right operand of '%', '<<', '>>', '&', '^' or '|' must have integral type. ",
		499:"Right operand of shift operator is greater than or equal to the width of the underlying type. ",
		500:"[U] Right operand of shift operator is negative - this is undefined. ",
		501:"[U] Right operand of shift operator is too large - this is undefined. ",
		502:"A right shift on signed data may be an arithmetic or a logical shift. ",
		503:"[U] Dereferencing NULL pointer. ",
		504:"[U] Dereferencing pointer value that is definitely NULL. ",
		505:"[U] Dereferencing pointer value that is apparently NULL. ",
		506:"Dereferencing pointer value that is possibly NULL. ",
		507:"[u] Arithmetic operation on NULL pointer. ",
		508:"[u] Arithmetic operation on pointer value that is definitely NULL. ",
		509:"[u] Arithmetic operation on pointer value that is apparently NULL. ",
		510:"Arithmetic operation on pointer value that is possibly NULL. ",
		513:"[C] Only compatible pointer types may be compared. ",
		514:"[C] Only compatible types may be compared. ",
		515:"[C] Only compatible pointer types may be compared. ",
		536:"[C] Left operand of '&&', '||' or '?' must have arithmetic or pointer type. ",
		537:"[C] Right operand of '&&' or '||' must have arithmetic or pointer type. ",
		540:"[C] Operands of conditional expressions must have compatible types. ",
		541:"[u] Argument no. %s does not have object type. ",
		542:"[C] Control expression must have arithmetic or pointer type. ",
		543:"[U] 'void' expressions have no value and may not be used in expressions. ",
		544:"[U] The value of an incomplete 'union' may not be used. ",
		545:"[U] The value of an incomplete 'struct' may not be used. ",
		546:"[C] 'enum %s' has unknown content. Use of an enum tag with undefined content is not permitted. ",
		547:"[U] This declaration of tag '%s' conflicts with a previous declaration. ",
		550:"[C] Left operand of '+=' or '-=' is a pointer to an object of unknown size. ",
		551:"[E] Cast may not operate on the left operand of the assignment operator. ",
		553:"Translation unit contains no object or function definitions with external linkage. ",
		554:"[C] 'static %s()' is used but no definition has been given. ",
		555:"[C] Assignment requires compatible types. ",
		556:"[C] Left operand of assignment must be a modifiable object. ",
		557:"[C] Right operand of assignment is not of arithmetic type. ",
		558:"[C] Right operand of '+=' or '-=' must have integral type. ",
		559:"[C] Right operand of '<<=', '>>=', '&=', '|=', '^=' or '%=' must have integral type. ",
		560:"[C] Left operand of '<<=', '>>=', '&=', '|=', '^=' or '%=' must have integral type. ",
		561:"[C] Right operand of assignment is not of compatible 'struct' or 'union' type. ",
		562:"[C] Right operand of assignment is a pointer to a differently qualified base type. ",
		563:"[C] Right operand of assignment does not have a compatible pointer type. ",
		564:"[C] Left operand of assignment must be an lvalue (it must designate an object). ",
		565:"[C] Left operand of '+=' or '-=' must have arithmetic type. ",
		580:"[C] Constant is too large for its type. ",
		581:"[C] Floating-point constant is too small for its type. ",
		584:"Division by value that is possibly zero. ",
		585:"[U] Division by value that is apparently zero. ",
		586:"[U] Division by constant zero value. ",
		587:"[U] Division by value that is definitely zero. ",
		588:"[C] Width of bit-field must be an integral constant expression. ",
		589:"[C] Enumeration constant must be an integral constant expression. ",
		590:"[C] Array bound must be an integral constant expression. ",
		591:"[C] 'case' expression must be an integral constant expression. ",
		594:"Negative 'case' label expression is incompatible with unsigned switch control expression. ",
		596:"Size of 'case' label expression is too large for type of switch control expression. ",
		597:"Type of 'case' label expression is not consistent with type of switch control expression. ",
		601:"[E] Function 'main()' is not of type 'int (void)' or 'int (int, char *[])'. ",
		602:"[U] The identifier '%s' is reserved for use by the library. ",
		604:"[C99] Declaration appears after statements in a compound statement. ",
		605:"[C] A declaration must declare a tag or an identifier. ",
		606:"Object '%s' is declared using typedefs which are different to those in a previous declaration. ",
		609:"[L] Number of modifiers in declarator exceeds 12 - program does not conform strictly to ISO:C90. ",
		611:"[L] Nesting of 'struct' or 'union' types exceeds 15 - program does not conform strictly to ISO:C90. ",
		612:"[L] Size of object '%s' exceeds 32767 bytes - program does not conform strictly to ISO:C90. ",
		614:"[L] Number of block scope identifiers exceeds 127 in a block - program does not conform strictly to ",
		616:"[C] Illegal combination of type and storage class specifiers. ",
		617:"[C] 'const' qualifier may not appear more than once. ",
		618:"[C] 'volatile' qualifier may not appear more than once. ",
		620:"[C] The variable '%s' cannot be implicitly initialized because it has unknown size. ",
		621:"[C] Cannot initialize '%s' because it has unknown size. ",
		622:"[C] '%s' has more than one declaration in the same scope and name space. ",
		623:"[U] '%s' has incomplete type and no linkage - this is undefined. ",
		624:"Function '%s' is declared using typedefs which are different to those in a previous declaration. ",
		625:"[U] '%s' has been declared with both internal and external linkage - the behaviour is undefined. ",
		626:"[u] '%s' has different type to previous declaration (which is no longer in scope). ",
		627:"[C] '%s' has different type to previous declaration in the same scope. ",
		628:"[C] '%s' has different type to previous in-scope declaration. ",
		629:"[C] More than one definition of '%s' (with internal linkage). ",
		630:"[U] More than one definition of '%s' (with external linkage). ",
		631:"[C] More than one declaration of '%s' (with no linkage). ",
		632:"[U] Tentative definition of '%s' with internal linkage cannot have unknown size. ",
		633:"[E] Empty structures and unions are a language extension. ",
		634:"[I] Bit-field is not declared explicitly as unsigned or signed. ",
		635:"[E] Bit-fields not of type int, signed int or unsigned int are not supported in ISO-C. ",
		636:"[U] There are no named members in this 'struct' or 'union'. ",
		637:"[S] Storage class specifier is illegal on 'struct' or 'union' member. ",
		638:"[C] Duplicate member name '%s' in 'struct' or 'union'. ",
		639:"[L] Number of members in 'struct' or 'union' exceeds 127 - program does not conform strictly to ISO:",
		640:"[C] '%s' in 'struct' or 'union' type may not have 'void' type. ",
		641:"[C] '%s' in 'struct' or 'union' type may not have function type. ",
		642:"[C] '%s' in 'struct' or 'union' type may not be an array of unknown size. ",
		643:"[C] '%s' in 'struct' or 'union' type may not be a 'struct' or 'union' with unknown content. ",
		644:"[C] Width of bit-field must be no bigger than the width of an 'int'. ",
		645:"[C] A zero width bit-field cannot be given a name. ",
		646:"[C] Enumeration constants must have values representable as 'int's. ",
		647:"[L] Number of enumeration constants exceeds 127 - program does not conform strictly to ISO:C90. ",
		648:"[S] No function header - possibly caused by a semicolon ';' after the function declaration. ",
		649:"[C] K&R style declaration of parameters is not legal after a function header that includes a paramet",
		650:"[C] Illegal storage class specifier on function parameter. ",
		651:"[C] Parameter identifiers may only be given in a function definition. ",
		652:"[u] Identifiers have been provided for some but not all of the parameters in a function prototype. ",
		653:"[C] Duplicate definition of 'struct', 'union' or 'enum' tag '%s'. ",
		654:"[U] Using 'const' or 'volatile' in a function return type is undefined. ",
		655:"[C] Illegal storage class specifier on function parameter. The only legal specifier is 'register'. ",
		656:"[C] Function return type cannot be function or array type, or incomplete 'struct' or 'union' type (f",
		657:"[C] No identifier is given in declaration of parameter. ",
		658:"[U] Parameter cannot have 'void' type. ",
		659:"[C] The identifier '%s' was not given in the parameter list. ",
		660:"Unnamed structure/union member. ",
		661:"[U] '%s()' may not have a storage class specifier of 'static' when declared locally. ",
		662:"[E] Accessing a member of a nested structure in this way is a language extension. ",
		664:"[C] Parameter cannot have '(void)' type. Perhaps the intention was to have a '(void)' parameter list",
		665:"[C] Duplicate parameter declaration for '%s'. ",
		666:"[S] Only type qualifiers 'const' or 'volatile' are legal here in a pointer declaration. ",
		667:"[U] '%s' is declared as a typedef and may not be redeclared in an inner scope without a type specifi",
		668:"[U] '%s' is declared as a typedef and may not be redeclared as a member of a 'struct' or 'union' wit",
		670:"[S] Function defined with invalid function header syntax. ",
		671:"[C] Arithmetic object requires arithmetic initializer. ",
		672:"[U] The initializer for a 'struct', 'union' or array is not enclosed in braces. ",
		673:"[C] Pointer initializer has a differently qualified base type. ",
		674:"[C] Pointer initializer does not have compatible type. ",
		675:"[U] Initializer for 'struct' or 'union' does not have compatible type. ",
		676:"[u] Array base type cannot have function type. QA C has assumed that 'pointer to function' was inten",
		677:"[C] Array size is negative, or unrepresentable. ",
		678:"[u] Array base is array of unknown size. Arrays cannot be constructed from incomplete types. ",
		679:"Redundant braces found in initializer. ",
		680:"[u] Array base is 'struct' or 'union' of unknown content. Arrays cannot be constructed from incomple",
		682:"[C] 'string' initializer given for 'char' object. ",
		683:"[C] L'string' initializer given for 'wchar_t' object. ",
		684:"[C] Too many initializers. ",
		685:"[C] Initializer for any object with static storage duration, must be a constant expression. ",
		686:"Array has fewer initializers than its declared size. Default initialization is applied to the remain",
		687:"Array has been initialized using concatenated strings and has fewer initializers than its declared s",
		688:"Array size determined by number of initializers which include concatenated string literals. ",
		689:"Initializer may be jumped over and never applied. ",
		690:"[C] String contains too many characters to initialize object. ",
		693:"Struct initializer is missing the optional {. ",
		694:"Array initializer is missing the optional {. ",
		695:"Type given in sizeof is not compatible with the pointed to type used to cast malloc. ",
		696:"The size of the allocated memory block is smaller than the size of the object type addressed by the ",
		697:"The size of the allocated memory block is not an integral multiple of the size of the object type ad",
		698:"[C] Arithmetic and pointer type objects require compatible scalar initializers. ",
		699:"[C] Pointer initializer does not have compatible type. ",
		702:"Result of sizeof operator is not explicitly cast. ",
		703:"Structure has fewer initializers than its declared size. Default initialization is applied to the re",
		706:"[u] Label '%s' is not unique within this function. ",
		708:"[C] No definition found for the label '%s' in this function. ",
		709:"[C] Initialization of locally declared 'extern %s' is illegal. ",
		715:"[L] Nesting of control structures (statements) exceeds 15 - program does not conform strictly to ISO",
		722:"Previous enum constants assigned a value explicitly. ",
		723:"initialize none, first only, or all entries in this enumerator list. ",
		735:"Using relational or logical operators in a switch expression is usually a programming error. ",
		736:"[C] 'case' label does not have unique value within this 'switch' statement. ",
		737:"[C] More than one 'default' label found in 'switch' statement. ",
		738:"[C] 'switch' control expression must have integral type. ",
		739:"[L] Number of 'case' labels exceeds 257 - program does not conform strictly to ISO:C90. ",
		744:"[U] '%s()' has been declared with a non void result type but ends with an implicit 'return ;' statem",
		745:"[U] 'return;' found in '%s()', which has been defined with a non-'void' return type. ",
		746:"[C] 'return exp;' found in '%s()' whose result type is 'void'. ",
		747:"[u] 'return exp;' found in '%s()' whose result has qualified 'void' type. ",
		750:"A union type specifier has been defined. ",
		752:"String literal passed as argument to function whose parameter is not const qualified. ",
		753:"String literal constant is addressed by a pointer which is not const qualified. ",
		755:"[C] 'return' expression does not have arithmetic type. ",
		756:"[C] 'return' expression does not have 'struct' or 'union' type compatible with function result type.",
		757:"[C] 'return' expression is a pointer to a differently qualified type than the function return type. ",
		758:"[C] 'return' expression does not have pointer type compatible with function return type. ",
		759:"An object of union type has been defined. ",
		766:"[C] 'continue' statement found outside a loop statement. ",
		767:"[C] 'break' statement found outside a loop or 'switch' statement. ",
		768:"[C] 'case' or 'default' found outside 'switch' statement. ",
		769:"This break statement terminates an iteration statement. ",
		770:"A continue statement has been used. ",
		771:"More than one break statement is being used to terminate an iteration statement. ",
		774:"[C] 'auto' may not be specified on global declaration of '%s'. ",
		775:"[C] '%s': 'register' may not be specified for global declaration. ",
		776:"[L] External identifier matches other identifier(s) (e.g. '%s') in first 6 characters - program does",
		777:"[U] External identifier does not differ from other identifier(s) (e.g. '%s') within the specified nu",
		778:"[L] Identifier matches other identifier(s) (e.g. '%s') in first 31 characters - program does not con",
		779:"[U] Identifier does not differ from other identifier(s) (e.g. '%s') within the specified number of s",
		780:"An identifier named '%s' has also been declared in another namespace. ",
		781:"'%s' is being used as a structure/union member as well as being a label, tag or ordinary identifier.",
		782:"An identifier named '%s' is subsequently declared in another namespace. ",
		783:"A subsequent declaration of '%s' means that it is being used both as a structure/union member and al",
		790:"This translation unit makes use of floating types. ",
		801:"[C] The '##' operator may not be the first token in a macro body. ",
		802:"[C] The '##' operator may not be the last token in a macro body. ",
		803:"[C] The '#' operator may only appear before a macro parameter. ",
		804:"[C] Macro parameter '%s' is not unique. ",
		805:"[S] Identifier expected in macro parameter list. ",
		806:"[S] Comma ',' expected in macro parameter list. ",
		807:"[S] Identifier missing in macro parameter list. ",
		808:"#include '%s' causes itself to be included recursively. QA C terminates execution after 8 occurren",
		809:"[U] The '#include' preprocessing directive has not been followed by <h-char-sequence> or \"s-char-seq",
		810:"[L] '#include '%s' causes nesting to exceed 8 levels - program does not conform strictly to ISO:C90",
		811:"[C] The glue operator '##' may only appear in a '#define' preprocessing directive. ",
		812:"[C] Header name token '<text>' found outside '#include' preprocessing directive. ",
		813:"[U] Using any of the characters ' \" or /* in '#include <%s>' gives undefined behaviour. ",
		814:"[U] Using the characters ' or /* in '#include '%s' gives undefined behaviour. ",
		815:"[L] #include <...> file name does not conform strictly to ISO:C90. ",
		816:"[L] #include '.' file name does not conform strictly to ISO:C90. ",
		817:"[S] Closing quote or bracket '>' missing from include filename. ",
		818:"Cannot find %s - Perhaps the appropriate search path was not given? ",
		819:"Cannot open %s - Perhaps the appropriate search path was not given? ",
		820:"[S] '#include' requires a header name. ",
		821:"[C] '#include %s' does not identify a header or source file that can be processed. ",
		823:"[S] Unexpected #else or #elif directive. #else or #elif directives cannot appear in an else branch o",
		824:"[S] Found '#else' or '#elif' without '#if..' preprocessing directive. ",
		825:"[S] Found '#endif' without '#if...' preprocessing directive. ",
		826:"[S] Found ':' without '?' in '#if' or #elif expression. ",
		827:"[S] Missing ':' after '?' in '#if' or #elif expression. ",
		828:"[L] Maximum '#if...' nesting exceeds 8 levels - program does not conform strictly to ISO:C90. ",
		829:"[S] Could not find '#endif' preprocessing directive to close '#if...'. ",
		830:"[E] Preprocessing directive may be followed by whitespace and new-line only. Comments may be used to",
		831:"[E] Use of '\\' in this '#include' line is a PC extension - this usage is non-portable. ",
		832:"Macro substitution in #include preprocessing directive. ",
		833:"[S] '#ifdef' or '#ifndef' must be followed by an identifier. ",
		834:"[C] Function-like macro '%s()' cannot be redefined as an object-like macro. ",
		835:"[C] Redefinition of '%s()' with different parameters. ",
		836:"[U] Definition of macro named 'defined'. ",
		837:"[U] Use of '#undef' to remove the operator 'defined'. ",
		838:"File has already been included directly from this file. ",
		839:"File has already been included indirectly from this file. ",
		841:"Use of #undef is not recommended in some programming standards. ",
		842:"Macro #define'd or #undef'd within a block. ",
		843:"/ character used in an include file name. ",
		844:"[C] Redefinition of '%s' with a different body. ",
		845:"[C] Redefinition of object-like macro '%s' as a function-like macro. ",
		846:"[S] '#define' must be followed by an identifier. ",
		847:"[S] '#undef' must be followed by an identifier. ",
		848:"[U] Use of '#undef' to remove '%s' which is predefined by the compiler. ",
		849:"[S] Preprocessing directive appears in the middle of a line. ",
		850:"[C99] Macro argument is empty. ",
		851:"[C] More arguments in macro call than specified in definition. ",
		852:"[C] Unable to find the ')' that marks the end of the macro call. ",
		853:"[U] Macro arguments contain a sequence of tokens that has the form of a preprocessing directive. ",
		854:"[U] Redefinition of '%s', which is a predefined macro name. ",
		855:"Preprocessing results in a sequence of tokens that has the form of a preprocessing directive. ",
		856:"[C] Fewer arguments in macro call than specified in definition. ",
		857:"[L] Number of macro definitions exceeds 1024 - program does not conform strictly to ISO:C90. ",
		858:"[L] Number of macro parameters exceeds 31 - program does not conform strictly to ISO:C90. ",
		859:"[L] Number of arguments in macro call exceeds 31 - program does not conform strictly to ISO:C90. ",
		861:"Contents of <%s> not referenced within source. ",
		862:"Contents of '%s' not referenced within source. ",
		863:"[S] '#line' must be followed by preprocessing tokens. ",
		864:"[U] '#line digit-sequence' does not specify a line number in the range 1 to 32767. ",
		865:"[U] '#line' directive does not match '#line digit-sequence \"s-char-sequence\"'. ",
		866:"[C] The string literal in a '#line' directive must be a character string literal. ",
		867:"[U] '#line' has not been followed by a line number. ",
		868:"An absolute path has been specified in a #include statement. ",
		869:"'#error' directive: %s Analysis terminated due to '#error' directive. ",
		872:"[U] Result of '##' operator is not a legal preprocessing token. ",
		873:"[C] Preprocessing token cannot be converted to an actual token. ",
		874:"[U] Character string literal and wide character string literal are adjacent. ",
		875:"[L] String literal exceeds 509 characters - program does not conform strictly to ISO:C90. ",
		877:"[C] '#if' and #elif expressions may contain only integral constants. ",
		878:"Using wide character or string literals. ",
		879:"[S] Illegal operator in '#if' or #elif expression. ",
		880:"Order of evaluation of # and ## operators is unspecified. ",
		881:"Order of evaluation of multiple ## operators is unspecified. ",
		882:"The contents of the forceincluded file '%s' have not been referenced ",
		883:"Include file code is not protected against repeated inclusion ",
		884:"Order of evaluation of multiple # operators is unspecified. ",
		885:"[U] The token 'defined' is generated in the expansion of this macro. ",
		886:"[S] '#if' and #elif require a constant expression. ",
		887:"[U] Use of 'defined' must match either 'defined(identifier)' or 'defined identifier'. ",
		888:"[U] 'defined' requires an identifier as an argument. ",
		889:"#undef'ing an identifier that has already been #undef'ed. ",
		890:"#ifdef'ing an identifier that has been #undef'ed (in nested #if). ",
		891:"#ifdef'ing an identifier that has been #undef'ed. ",
		896:"[S] Missing operand in '#if' or #elif expression. ",
		897:"[S] Missing operator in '#if' or #elif expression. ",
		898:"[S] Unmatched ')' or missing '?' in '#if' or #elif expression. ",
		899:"[C] The '#' token may appear only as a punctuator in a directive or operator in a '#define'. ",
		901:"Source skipped to this point after error in top level declaration. ",
		902:"Source skipped to this point after error in parameter declaration. ",
		903:"Source skipped to this point after error in member declaration. ",
		904:"[S] Invalid designator. ",
		907:"[S] Unexpected token. ",
		911:"Inserted '%s' token in an attempt to continue parsing. ",
		913:"Source skipped to this point after error in 'case' label. ",
		917:"[S] Unable to recover from syntax errors in this source file. ",
		918:"Source too complex. Please report this problem to Programming Research Technical Support. ",
		920:"Source skipped to this point after error in expression. ",
		925:"[S] Unexpected end of file. ",
		926:"[S] Expected:%s. ",
		927:"[S] Unexpected ')'. ",
		928:"[S] Missing comma ',' between enumerators. ",
		930:"[C99] Trailing comma at the end of an enumerator-list. ",
		940:"[C] Illegal usage of a variably modified type. ",
		941:"[C] A variable length array may not be initialized. ",
		942:"[U] A * can only be used to specify array size within function prototype scope. ",
		943:"[C] Jump to label '%s' is a jump into the scope of an identifier with variably modified type. ",
		944:"[C] The label '%s' is inside the scope of an identifier with variably modified type. ",
		945:"[C99] WARNING. Operand of sizeof has a type which is a variable length array type. ",
		970:"Unable to create preprocessed file. ",
		1001:"[E] '#include %s' is a VMS extension. ",
		1002:"[E] '%s' is not a legal identifier in ISO C. ",
		1003:"[E] '#%s' is a language extension for in-line assembler. All statements located between #asm and #en",
		1004:"[S] '#endasm' found without matching '#asm' preprocessing directive. ",
		1005:"[S] End-of-file encountered when expecting '#%s' preprocessing directive. ",
		1006:"[E] This in-line assembler construct is a language extension. The code has been ignored. ",
		1008:"[E] '#%s' is not a legal ISO C preprocessing directive. ",
		1009:"[S] Unrecognizable expression in '#if' preprocessing directive. ",
		1010:"[S] '#%s' is not a valid form of '#if' syntax . ",
		1011:"[C99] Use of C++ comment '//'. ",
		1012:"[S] Use of C++ reference operator '&' will cause syntax errors in ISO C. ",
		1013:"[S] '&' is not legal here - treated as '*'. ",
		1014:"[E] Unusual type specification - this will be treated as a language extension. ",
		1015:"[E] '%s' is not a legal keyword in ISO C. ",
		1018:"[C99] Using LL suffix. ",
		1019:"[E] '@ address' is not supported in ISO C. ",
		1020:"[E] '__typeof__' is not supported in ISO C, and is treated as a language extension. ",
		1021:"[E] A statement expression is not supported in ISO C, and is treated as a language extension. ",
		1022:"[E] '__alignof__' is not supported in ISO C, and is treated as a language extension. ",
		1023:"[C] Using '__alignof__' on function types is illegal. ",
		1024:"[C] Using '__alignof__' on incomplete types is illegal. ",
		1025:"[C] Using '__alignof__' on bit-fields is illegal. ",
		1026:"[E] The indicated @word construct has been ignored. ",
		1027:"[C99] Using type 'long long'. ",
		1028:"[E] Use of the sizeof operator in a preprocessing directive is a language extension. ",
		1029:"[E] Whitespace encountered between backslash and new-line has been ignored. ",
		1030:"[C99] Macro defined with variable argument list. ",
		1031:"[C99] Initializer for 'struct', 'union' or array type is not a constant expression. ",
		1033:"[C] The identifier __VA_ARGS__ may only be used in the replacement list of a variadic macro. ",
		1034:"[E] Macro defined with named variable argument list. This is a language extension. ",
		1035:"[E] No macro arguments supplied for variable argument list. This is a language extension. ",
		1036:"[E] Comma before ## ignored in expansion of variadic macro. This is a language extension. ",
		1037:"[E] Arrays of length zero are a language extension. ",
		1038:"[E] The sequence ', ##__VA_ARGS__' is a language extension. ",
		1041:"[E] Empty aggregate initializers are a language extension. ",
		1051:"[C99] A variable length array has been declared. ",
		1052:"[C99] A variable length array of unspecified size has been declared. ",
		1053:"[C99] Designators have been used in this initialization list. ",
		1054:"[C99] A compound literal has been used. ",
		1100:"The label '%s' is also declared as a typedef. ",
		1250:"Unsuffixed integer constant causes implicit conversion of other (integral) operand. ",
		1251:"Suffixed integer constant causes implicit conversion of other (integral) operand. ",
		1252:"Suffixed integer constant implicitly converted to different integer type. ",
		1253:"Unsuffixed integer constant implicitly converted to different integer type. ",
		1254:"Suffix is not consistent with resulting type of integer constant. ",
		1255:"Unsuffixed integer constant is not of type int. ",
		1256:"Suffixed integer constant implicitly converted to different integer type on assignment. ",
		1257:"Suffixed integer constant implicitly converted to smaller integer type on assignment. ",
		1258:"Suffixed integer constant explicitly cast to another type. ",
		1259:"Unsuffixed integer constant explicitly cast to another type. ",
		1260:"Integer constant implicitly converted to a floating type. ",
		1261:"Suffixed floating constant implicitly converted to different floating type. ",
		1262:"Unsuffixed floating constant implicitly converted to different floating type. ",
		1263:"Floating constant causes implicit conversion of other (integral) operand. ",
		1264:"Suffixed floating constant implicitly converted to different floating type on assignment. ",
		1265:"Unsuffixed floating constant implicitly converted to different floating type on assignment. ",
		1266:"Floating constant implicitly converted to an integral type on assignment. ",
		1267:"Suffixed floating constant explicitly cast to another type. ",
		1268:"Unsuffixed floating constant explicitly cast to another type. ",
		1269:"Floating constant explicitly cast to integral type. ",
		1271:"Using a non-int expression does not alter the type of the enum constant. ",
		1272:"Redundant leading zeroes on a numeric constant. ",
		1274:"Unsuffixed floating constant causes implicit conversion of other (floating) operand. ",
		1275:"Suffixed floating constant causes implicit conversion of other (floating) operand. ",
		1276:"Integer constant implicitly converted to floating type on assignment. ",
		1277:"A 'U' suffix has not been appended to a hex constant. ",
		1278:"A suffix has been appended to a decimal integer constant. ",
		1279:"An 'L' suffix has been appended to a hex constant. ",
		1280:"A lowercase letter L (l) has been used in an integer or floating suffix. ",
		1281:"Integer literal constant is of an unsigned type but does not include a 'U' suffix. ",
		1300:"'%s' is a keyword in C++. ",
		1301:"'%s' is a keyword in some C++ implementations. ",
		1302:"'%s()' must be declared before use in C++. ",
		1303:"An empty parameter list in a function type has a different meaning in C++. ",
		1304:"Old style definition of function '%s()' is not portable to C++. ",
		1305:"The global variable '%s' is declared 'const', but neither 'static' nor 'extern' has been specified -",
		1306:"Multiple tentative definitions of '%s' - this will work in C but not in C++. ",
		1307:"Unnamed 'struct' and 'union' types may cause portability problems when moving to C++. ",
		1308:"The tag '%s' would clash with an existing typedef in C++. ",
		1309:"The typedef '%s' would clash with an existing 'struct' / 'union' / 'enum' tag in C++. ",
		1310:"'%s' is used as a tag and a typedef for the same 'struct' / 'union' / 'enum'. ",
		1311:"C++ does not allow this implicit conversion between 'void *' and 'const T *'. ",
		1312:"The array being initialized will not hold the terminating '\\0' for the string initializer. ",
		1313:"Executing 'goto %s' will cause local initialization to be skipped - this is illegal in C++. ",
		1314:"The tag '%s' is defined within another 'struct' / 'union'. ",
		1315:"The 'static' qualifier has been used in the declaration of a tag. ",
		1317:"Value not in the enumeration type. ",
		1318:"Composite assignment operators cannot be used on objects with enumerated type in C++. ",
		1319:"Increment and decrement operators cannot be applied to objects with enumerated type in C++. ",
		1322:"In C, sizeof('c') == sizeof(int), but in C++, sizeof('c') == sizeof(char) == 1. ",
		1323:"The size of an enumerated constant is not guaranteed to be sizeof(int) in C++. ",
		1324:"You cannot call 'main' or take its address in C++. ",
		1325:"'%s()' is defined with a non-void return type but contains 'return;'. This is not allowed in C++. ",
		1327:"No guarantees are made about the value or presence of the macro __STDC__ in C++. ",
		1328:"Tag type defined within a function declaration. ",
		1329:"In C++, objects declared 'const' must be initialized unless they are explicitly declared 'extern'. ",
		1330:"The parameter identifiers in this function declaration differ from those in a previous declaration. ",
		1331:"Type or number of arguments doesn't match previous use of the function. ",
		1332:"Type or number of arguments doesn't match prototype found later. ",
		1333:"Type or number of arguments doesn't match function definition found later. ",
		1334:"The parameter identifiers in the prototypes of these functions/function pointers are different. ",
		1335:"Parameter identifiers missing in function prototype declaration. ",
		1336:"Parameter identifiers missing in declaration of a function type. ",
		1400:"Equality comparison with enum constant from enum of different type. ",
		1401:"Argument passed is constant enum not in enum type. ",
		1402:"Assignment of constant enum not in enum type. ",
		1403:"Return of constant enum not in enum type. ",
		1404:"Comparison with constant enum not in enum type. ",
		1410:"Equality comparison of an enum with a numeric constant. ",
		1411:"Argument passed is a numeric constant but an enum is expected. ",
		1412:"Constant expression assigned to an enum. ",
		1413:"Return of numeric constant when enum expected. ",
		1414:"Relational comparison of an enum with a numeric constant. ",
		1420:"Equality comparison with enum object of different type. ",
		1421:"Argument passed is enum object of different type. ",
		1422:"Assignment of enum object of different type. ",
		1423:"Return of enum object of different type. ",
		1424:"Comparison with enum object of different type. ",
		1431:"Argument passed is enum when non enum type expected. ",
		1432:"Assignment of enum to non enum type. ",
		1433:"Return of enum to non enum type. ",
		1434:"This enum constant is not representable in a 16 bit integer type. ",
		1440:"Equality comparison between enum and non enum types. ",
		1441:"Argument passed is non enum type when enum expected, and may be out of range. ",
		1442:"Expression assigned to an enum. ",
		1443:"Return of non enum type to enum, and may be out of range. ",
		1444:"Comparison of non enum type to enum. ",
		1460:"Switch label value, %s, not contained in enum type. ",
		1461:"Value is not in enum type, but is bitwise or of enum constants in type. ",
		1470:"Numeric constant used as case label with switch expression of enum type. ",
		1472:"Case label belongs to different enum type. ",
		1473:"Operands of : operator are different enum types. ",
		1474:"Performing bitwise operation on enum values. ",
		1475:"Range of possible enum values suggests this test is always true. ",
		1476:"Range of possible enum values suggests this test is always false. ",
		1477:"Object of enum type being implicitly compared against zero, a non symbolic name. ",
		1478:"Object of enum type, not having a zero value, is being implicitly compared against zero. ",
		1479:"Arithmetic being performed on enumerated object. ",
		1480:"Operands of bitwise operator are different enum types. ",
		1481:"Unary operator being applied to enum type. ",
		1482:"Expression cast to enumeration type. ",
		1483:"Enum object or constant passed as argument to old style function declaration. ",
		1484:"Constant expression cast to enumeration type. ",
		1500:"The object 'name' is declared but is not used within this project. ",
		1501:"The function 'name' is declared but is not used within this project. ",
		1502:"The object 'name' is defined but is not used within this project. ",
		1503:"The function 'name' is defined but is not used within this project. ",
		1504:"The object 'name' is only referenced in the translation unit where it is defined. ",
		1505:"The function 'name' is only referenced in the translation unit where it is defined. ",
		1506:"The identifier 'name' is declared as a typedef and is used elsewhere for a different kind of declara",
		1507:"'name' is used as a typedef for different types. ",
		1508:"The typedef 'name' is declared in more than one location. ",
		1509:"'name' has external linkage and has multiple definitions. ",
		1510:"'name' has external linkage and has incompatible declarations. ",
		1512:"Identifier 'name' with external linkage has separate declarations in multiple translation units. ",
		1513:"Identifier 'name' with external linkage has separate non-defining declarations in more than one loca",
		1514:"The object 'entity' is only referenced by function 'func', in the translation unit where it is defin",
		1515:"Different files are being used which have the same filename 'filename'. ",
		1516:"Different files are being used which have similar filenames 'filename', but with different case. ",
		1517:"Different files are being used which have the same filename 'filename', and one includes the other. ",
		1520:"Functions are indirectly recursive. ",
		1525:"Object/function with external linkage has same identifier as another object/function with internal l",
		1526:"Object with no linkage has same identifier as another object/function with external linkage. ",
		1527:"Object/function with internal linkage has same identifier as another object/function with internal l",
		1528:"Object with no linkage has same identifier as another object/function with internal linkage. ",
		1529:"Object with no linkage has same identifier as another object with static storage duration but no lin",
		1531:"The object 'name' is referenced in only one translation unit - but not the one in which it is define",
		1532:"The function '%1s' is only referenced in one translation unit - but not the one in which it is defin",
		1533:"The object 'entity' is only referenced by function 'func'. ",
		1540:"Unable to open file 'filename'. ",
		1576:"Label statement here. ",
		1577:"Next seen here. ",
		1578:"Found in directory: 'directory'. ",
		1579:"Referenced here. ",
		1580:"Function 'func1' calls 'func2' here. ",
		1581:"kind decl here. ",
		1582:"Previously seen here. ",
		1592:"'id' declared in classKind 'className'. ",
		1593:"'id' defined here. ",
		1594:"'id' declared here. ",
		1599:"Included from here. ",
		1690:"Null preprocessing directive encountered. ",
		1691:"Null preprocessing directive encountered in excluded section of code. ",
		2001:"A 'goto' statement has been used. ",
		2002:"No 'default' case found in this 'switch' statement. ",
		2003:"The preceding non-empty 'case' or 'default' clause does not end with an explicit 'break' or 'return'",
		2004:"No concluding 'else' exists in this 'if'-'else'-'if' statement. ",
		2005:"Use of 'continue'. If this could be replaced by 'if'-'else', the program might be easier to read. ",
		2006:"'%s()' has more than one 'return' path. ",
		2007:"'auto' does not add information to a declaration, and is best avoided. ",
		2008:"Code statements precede the first label in this switch construct. ",
		2009:"This default label is not the final case label within the switch block. ",
		2010:"The function '%s()' must not be called. ",
		2015:"This label is not a case or default label for a switch statement. ",
		2016:"This switch statement default clause is empty. ",
		2017:"Comment spans more than one line. ",
		2018:"This switch default label is unreachable. ",
		2019:"Switch label is located within a nested code block. ",
		2020:"Final switch clause does not end with an explicit 'break' statement. ",
		2050:"The 'int' type specifier has been omitted from a function declaration. ",
		2051:"The 'int' type specifier has been omitted from an object declaration. ",
		2100:"Integral promotion : unsigned char promoted to signed int. ",
		2101:"Integral promotion : unsigned short promoted to signed int. ",
		2102:"Integral promotion : unsigned char promoted to unsigned int. ",
		2103:"Integral promotion : unsigned short promoted to unsigned int. ",
		2104:"Integral promotion : signed char promoted to signed int. ",
		2105:"Integral promotion : signed short promoted to signed int. ",
		2106:"Integral promotion : plain char promoted to signed int. ",
		2107:"Integral promotion : plain char promoted to unsigned int. ",
		2110:"Default argument promotion : unsigned char promoted to signed int. ",
		2111:"Default argument promotion : unsigned short promoted to signed int. ",
		2112:"Default argument promotion : unsigned char promoted to unsigned int. ",
		2113:"Default argument promotion : unsigned short promoted to unsigned int. ",
		2114:"Default argument promotion : signed char promoted to signed int. ",
		2115:"Default argument promotion : signed short promoted to signed int. ",
		2116:"Default argument promotion : plain char promoted to signed int. ",
		2117:"Default argument promotion : plain char promoted to unsigned int. ",
		2118:"Default argument promotion : float promoted to double. ",
		2200:"Indentation of this line is to the left of the line above. ",
		2201:"This indentation is not consistent with previous indentation in this file. ",
		2203:"This closing brace is not aligned appropriately with the matching opening brace. ",
		2204:"'%s' is not aligned to match its controlling 'switch' statement. ",
		2205:"More than one declaration or statement on the same line. ",
		2207:"This brace style is not consistent with 'K&R' style. ",
		2208:"This brace style is not consistent with 'indented' style. ",
		2209:"This brace style is not consistent with 'exdented' style. ",
		2210:"A tab character has been used to indent source code. ",
		2211:"'%s' is not aligned with the previously declared identifier. ",
		2212:"Body of control statement is not enclosed within braces. ",
		2213:"Matching braces appear on the same line - proper indentation would be preferred. ",
		2214:"Body of control statement is on the same line and is not enclosed within braces. ",
		2215:"Indentation is not consistent with configured depth. ",
		2216:"More than one structure or union member declared on the same line. ",
		2217:"Line length exceeds %s characters. ",
		2461:"Control variable, %s, does not have block scope. ",
		2462:"Control variable, %s, is not initialized in this for loop expression. ",
		2463:"Control variable, %s, does not appear in the increment expression. ",
		2464:"Control variable, %s, modified twice in loop header. ",
		2465:"This 'for' loop will only be executed once. ",
		2466:"The value of this control expression is always 'false'. The contained code is unreachable. ",
		2467:"Control variable, %s, not modified inside loop. ",
		2468:"Control variable, %s, with file scope, not modified inside loop. ",
		2469:"Control variable, %s, modified in body of loop. ",
		2470:"Taking address of loop control variable, %s. ",
		2471:"Unable to deduce the loop control variable. ",
		2472:"More than one possible loop control variable. ",
		2547:"Use of tag '%s' hides more global declaration. ",
		2711:"'register' is only a hint - the compiler may well be able to do a better job of optimising - avoid! ",
		3001:"Function has been declared with an empty parameter list. ",
		3002:"Defining '%s()' with an identifier list and separate parameter declarations is an obsolescent featur",
		3003:"This token is a suspicious NULL pointer constant. ",
		3006:"This function contains a mixture of in-line assembler statements and C statements. ",
		3007:"void' has been omitted when defining a function with no parameters. ",
		3101:"Unary '-' applied to an operand of type unsigned int or unsigned long gives an unsigned result. ",
		3102:"Unary '-' applied to an operand whose underlying type is unsigned. ",
		3103:"Integer division or remainder operation with an operand whose underlying type is signed or negative.",
		3104:"#pragma '%s' has invalid arguments and has been ignored. ",
		3105:"A #pragma block has not been closed with a #pragma %s. ",
		3106:"This preprocessing directive has been ignored because it lies within a #pragma block. '#pragma %s' e",
		3107:"A '#pragma %s' has been found without a matching #pragma block start directive. ",
		3108:"Nested comments are not recognized in the ISO standard. ",
		3109:"Empty statement (';' on its own) - if this is deliberate, it is best to put ';' on a line by itself.",
		3110:"The left-hand operand of this ',' has no side-effects. ",
		3111:"This comma can be omitted from the end of the initializer with no effect. ",
		3112:"This statement has no side-effect - it can be removed. ",
		3113:"[U] 'return' statement includes no expression but function '%s()' is implicitly of type 'int'. ",
		3114:"[U] Function '%s()' is implicitly of type 'int' but ends without returning a value. ",
		3115:"Unrecognized preprocessing directive - ignored because it occurs in a FALSE arm of a '#if' group. ",
		3116:"Unrecognized #pragma arguments '%s' This #pragma directive has been ignored. ",
		3117:"expected 'on' or 'off' after '#pragma' flag. ",
		3118:"The #line directive may confuse development tools. ",
		3120:"Hard-coded 'magic' integer constant '%s'. ",
		3121:"Hard-coded 'magic' floating constant '%s'. ",
		3122:"Hard-coded 'magic' string literal. ",
		3123:"Hard coded 'magic' character constant %s. ",
		3131:"Hard coded 'magic' number '%s' used to define the size of a bit-field. ",
		3132:"Hard coded 'magic' number '%s' used to define the size of an array. ",
		3138:"Null statement is located close to other code or comments. ",
		3139:"Null statement is obscured by code or comment on the same line. ",
		3140:"Null statement occurs on a line by itself without comment. ",
		3141:"Null statement does not occur on a line by itself. ",
		3195:"The function parameter '%s' is always modified before use. ",
		3196:"The variable '%s' is never set. ",
		3197:"This initialization is redundant. The value of '%s' is never used before being modified. ",
		3198:"This assignment is redundant. The value of '%s' is never used before being modified. ",
		3199:"This assignment is redundant. The value of '%s' is never subsequently used. ",
		3200:"'%s' returns a value which is not being used. ",
		3201:"This statement is unreachable. ",
		3202:"The label '%s:' is not used in this function and could be removed. ",
		3203:"The variable '%s' is set but never used. ",
		3204:"The variable '%s' is only set once and so it could be declared with the 'const' qualifier. ",
		3205:"The identifier '%s' is not used and could be removed. ",
		3206:"The parameter '%s' is not used in this function. ",
		3207:"File scope static, '%s', is not used, and could be removed. ",
		3208:"'%s()' returns a value which is sometimes ignored. ",
		3209:"'%s()' returns a value which is always ignored. ",
		3210:"The global identifier '%s' is declared but is not used. ",
		3211:"The global identifier '%s' is defined but not used. ",
		3212:"This explicit cast is redundant and could be removed. ",
		3216:"Address of local static data assigned to pointer with linkage or wider scope. ",
		3217:"Address of automatic data assigned to pointer with linkage or wider scope. ",
		3218:"File scope static, '%s', is only accessed in one function. ",
		3219:"Static function '%s()' is not used within this translation unit. ",
		3220:"Identifier declared at a nested level of block scope. ",
		3221:"Function declared at block scope. ",
		3222:"Object with linkage declared at block scope. ",
		3223:"Identifier with static storage duration declared at block scope. ",
		3224:"This identifier has previously been declared with internal linkage but is not declared here with the",
		3225:"Function parameter returns address of automatic data. ",
		3226:"The result of an assignment operator is being used in an expression. ",
		3227:"The parameter '%s' is never modified and so it could be declared with the 'const' qualifier. ",
		3228:"Storage class specifier not positioned at the beginning of declaration. ",
		3229:"File scope static, '%s', is written but never used. ",
		3230:"Address of automatic data assigned to local pointer with static storage duration. ",
		3231:"Function parameter returns address of local static data. ",
		3232:"File scope static, '%s', is never written. It could be declared const. ",
		3233:"File scope static, '%s', is not explicitly initialized but its value is used. ",
		3234:"Declarations precede the first label in this switch construct. ",
		3296:"This implicit conversion of a non-negative integer expression will definitely result in truncation. ",
		3297:"This implicit conversion of a non-negative integer expression will apparently result in truncation. ",
		3301:"Unsigned left shift operation << in constant expression truncates bits from result. ",
		3302:"Unsigned subtraction in constant expression wraps around past zero. ",
		3303:"Unsigned addition in constant expression wraps around past maximum value. ",
		3304:"Unsigned multiplication in constant expression wraps around past maximum value. ",
		3305:"Pointer cast to stricter alignment. ",
		3306:"This implicit conversion of a non-negative constant integer value to an unsigned type will result in",
		3307:"The operand of 'sizeof' is an expression with implied side-effects, but they will not be evaluated. ",
		3308:"'%s()' has been declared 'static' but no definition is present. This is redundant. ",
		3309:"Control expression of this 'switch' statement is constant. ",
		3311:"[u] Jump to label '%s' from outside this block. Local initialization will not be performed. ",
		3312:"[u] The label '%s' is in a block with local initialization which will not be performed. ",
		3313:"No definition has been found for structure/union tag '%s'. ",
		3314:"This control expression is an assignment. It would be better practice to test the result against zer",
		3315:"This 'switch' statement contains only a single path - it is redundant. ",
		3316:"Dangerous comparison of unsigned data with zero. ",
		3317:"'#if...' not matched by '#endif' in included file. This is probably an error. ",
		3318:"'#else'/'#elif'/'#endif' in included file matched '#if...' in parent file. This is probably an error",
		3319:"[U] Function called with number of arguments which differs from number of arguments of definition. ",
		3320:"Type of argument no. %s differs from its type in definition of function. ",
		3321:"[U] The variable '%s' is definitely unset at this point. ",
		3322:"The operand of this logical negation operator '!' is not a Boolean value. ",
		3323:"This control loop condition has a constant 'true' value. ",
		3324:"An unsigned value is always greater than or equal to zero - this test is always true. ",
		3325:"This control expression has a constant 'false' value. ",
		3326:"An assignment operator is being used in a boolean expression. ",
		3328:"An unsigned value is being compared with a negative constant - this is dangerous. ",
		3330:"'%s()' has been called with a variable number of arguments. ",
		3332:"The macro '%s' used in this '#if...' test is not defined. ",
		3333:"A break statement is being used to exit from a switch case block but is not the final statement in t",
		3334:"This declaration of '%s' hides a more global declaration. ",
		3335:"No function declaration. Implicit declaration inserted: 'extern int %s();'. ",
		3337:"The array '%s[]' has unknown size, but storage will be allocated in this module for it. In order to ",
		3340:"Floating point variable used as 'for' loop index. ",
		3341:"Comparing floating point expressions for equality (with '==' or '!='). ",
		3342:"Control expression of 'for' loop is a floating point comparison. ",
		3343:"Logical NOT being performed on one operand of a comparison. ",
		3344:"Value of control expression is not derived from an explicit logical operation. ",
		3345:"Expression contains more than one access to objects that are volatile. ",
		3346:"This 'if' control expression has a constant 'true' value. ",
		3347:"[U] The variable '%s' is apparently unset at this point. ",
		3348:"This function argument points to data that is definitely unset. ",
		3349:"This function argument points to data that is apparently unset. ",
		3352:"This 'switch' statement contains only two execution paths. ",
		3353:"The variable '%s' is possibly unset at this point. ",
		3354:"This function argument points to data that is possibly unset. ",
		3355:"The result of this logical operation is always 'true'. ",
		3356:"The result of this logical operation is always 'false'. ",
		3357:"The value of this loop control expression is always 'true'. ",
		3358:"The value of this 'if' control expression is always 'true'. ",
		3359:"The value of this control expression is always 'false'. ",
		3360:"The value of this 'do - while' control expression is always 'false'. The loop will only be executed ",
		3361:"This 'do - while' control expression has a constant, 'false' value. The loop will only be executed o",
		3371:"Unsigned left shift operation << definitely truncates bits from result. ",
		3372:"Unsigned arithmetic definitely results in wraparound past zero. ",
		3381:"Unsigned left shift operation << apparently truncates bits from result. ",
		3382:"Unsigned arithmetic apparently results in wraparound past zero. ",
		3389:"Operator in the set + - * / % used with % operator. Extra parentheses recommended. ",
		3390:"Expression is equivalent to: '%s' ",
		3391:"Ternary operator used more than once. Extra parentheses recommended. ",
		3392:"A shift, relational or equality operator has been used more than once. Extra parentheses recommended",
		3393:"Different binary operators in the set + - * / with the same precedence have been used. Extra parenth",
		3394:"Binary operator other than + - * / % used with different binary operator of the same precedence. Ext",
		3395:"Operators in the set + - * / with different precedence have been used. Extra parentheses recommended",
		3396:"Ternary operator used with another binary operator. Extra parentheses recommended. ",
		3397:"Binary operator other than + - * / % used with binary operator of different precedence. Extra parent",
		3398:"Operator in set () [] -> . used with && or ||. Extra parentheses recommended. ",
		3399:"Unary operator used with && or ||. Extra parentheses recommended. ",
		3400:"Binary/ternary operator used with && or ||. Extra parentheses recommended. ",
		3401:"Possible precedence confusion: extra parentheses are recommended here. ",
		3402:"Braces are needed to clarify the structure of this 'if'-'if'-'else' statement. ",
		3403:"This sequence of operators is difficult to read without spaces. ",
		3404:"*p++ means *(p++) not (*p)++. The * operator is redundant. ",
		3405:"Index[Array] is equivalent to Array[Index] but more confusing. ",
		3406:"Object/function '%s', with external linkage, has been defined in a header file. ",
		3407:"String literal compared using a relational operator. ",
		3408:"'%s' has external linkage but is being defined without any previous declaration. ",
		3409:"The body of function-like macro '%s' is not enclosed in (). ",
		3410:"Macro parameter not enclosed in (). ",
		3411:"Macro defined with unbalanced brackets, parentheses or braces. ",
		3412:"Macro defines an unrecognized code-fragment. ",
		3413:"Macro definition could be replaced by a typedef. ",
		3414:"Macro defines a storage-class specifier keyword. ",
		3415:"The right hand operand of '&&' or '||' has side effects. ",
		3416:"This boolean expression contains side effects. ",
		3417:"The comma operator has been used outside a for-loop header. ",
		3418:"The comma operator has been used in a for-loop header. ",
		3419:"Initialization expression of 'for' statement has no side effects. ",
		3420:"Increment expression of 'for' statement has no side effects. ",
		3422:"Expression statement contains redundant operator at top level. ",
		3423:"Expression statement contains redundant cast at top level. ",
		3424:"Perhaps a logical operator rather than a bitwise operator intended. ",
		3425:"One side of ':' expression has no side effect. ",
		3426:"Right hand side of comma expression has no side effect and its value is not used. ",
		3427:"Right hand side of logical operator has no side effect. ",
		3428:"Macro defines a type qualifier keyword. ",
		3429:"A function-like macro is being defined. ",
		3430:"Macro argument expression requires parentheses. ",
		3431:"Macro defines a control statement keyword, operator or punctuator ",
		3435:"Parameter '%s' is used more than once in this macro definition. ",
		3436:"Macro definition hides previously declared identifier. ",
		3437:"[u] The assert macro has been suppressed to call a function of that name, undefined behaviour. ",
		3438:"[U] #undef'ing the assert macro to call a function of that name causes undefined behaviour. ",
		3439:"Macro redefines a keyword. ",
		3440:"Result of ++ or -- operator used in expression. ",
		3441:"Function call argument contains side effects. ",
		3442:"Operator other than & (address) or = (assignment) applied to a volatile object. ",
		3443:"Recursive macro definition detected: '%s'. ",
		3446:"The result operands of this conditional operator generate side effects ",
		3447:"'%s' has external linkage but this declaration is not in a header file. ",
		3448:"Declaration of typedef '%s' is not in a header file although it is used in a definition or declarati",
		3450:"Function '%s', with internal linkage, is being defined without a previous declaration. ",
		3451:"The global identifier '%s' has been declared in more than one file. ",
		3452:"The body of object-like macro '%s' is not enclosed in (). ",
		3453:"A function could probably be used instead of this function-like macro. ",
		3454:"Macro argument contains an increment, decrement or (compound) assignment operator. ",
		3455:"Macro argument contains a function call. ",
		3456:"Parameter '%s' will be evaluated more than once when this macro is used. ",
		3457:"Macro defines a braced initializer. ",
		3458:"Macro defines a braced code statement block. ",
		3459:"Macro defines a 'do-while-zero' construct. ",
		3460:"Macro defines a type specifier keyword. ",
		3461:"Macro defines a storage-class specifier/type qualifier sequence. ",
		3470:"The operand of 'sizeof' is not an expression which designates either an object or a type. ",
		3480:"Object/function '%s', with internal linkage, has been defined in a header file. ",
		3501:"This could be read as an old-style assignment operator. Spaces are needed to make it more readable. ",
		3600:"The unary plus operator is not available in K&R C. ",
		3601:"Trigraphs (??x) are an ISO feature. ",
		3602:"The keyword '%s' is not available in K&R C. ",
		3603:"Initialization of externals not available in K&R C. ",
		3604:"Local arrays and structures cannot be initialized in K&R C. ",
		3605:"'switch' must have an 'int' in K&R C. ISO C allows any integral type. ",
		3606:"Value has type 'long' in ISO C, but would have type 'unsigned int' in K&R C. ",
		3607:"Parameter '%s' is declared as a function and is implicitly converted to a pointer to a function. ",
		3608:"A '#elif' preprocessing directive has been used. ",
		3609:"'\\a' is an ISO escape sequence and may not be available on all compilers. ",
		3610:"Hexadecimal escape sequence used. ",
		3611:"Non-portable comparison of plain char with negative constant. ",
		3612:"Nonportable comparison of plain 'char' with zero. ",
		3613:"Some pre-ISO compilers would treat this 8 or 9 as an octal digit. ",
		3614:"Macro '%s' has been redefined without removing the previous definition with #undef. ",
		3615:"'entry' was a keyword in K&R C. ",
		3616:"Character constants may have different values in preprocessor arithmetic than in actual code. ",
		3617:"'struct' / 'union' assignment is not supported by old compilers. ",
		3618:"Not all compilers allow whitespace between '#' and the preprocessing directive. ",
		3619:"Not all compilers allow whitespace before preprocessing directives. ",
		3620:"'register' may be illegal on array and 'struct' / 'union' types in some compilers. ",
		3621:"Bit-fields are not portable - some old compilers do not even support them. ",
		3623:"Passing a structure or union to a function by value. ",
		3624:"Function returns a structure or union by value. ",
		3625:"Type 'char' has been used in the declaration of an object or a function. ",
		3626:"Double quote character in a character constant is not preceded by a backslash character. ",
		3627:"Single quote character in a string literal is not preceded by a backslash character. ",
		3628:"Octal escape sequences used in a character constant or string literal. ",
		3629:"Union contains member of floating type. ",
		3631:"Type 'char' has been used in a cast. ",
		3632:"Type 'char' has been used in the declaration of a typedef. ",
		3633:"Type 'char' has been used in the operand of the sizeof operator. ",
		3635:"Function identifier used as a pointer without a preceding & operator. ",
		3650:"Typedef defines an array type of unknown size. ",
		3651:"Using a typedef for an array of unknown size can lead to unexpected results. ",
		3660:"Named bit-field consisting of a single bit declared with a signed type. ",
		3661:"Nonportable comparison of plain int bit-field with zero. ",
		3662:"Non-portable comparison of plain int bit-field with negative constant. ",
		3663:"Structure declaration includes an unnamed bit-field. ",
		3664:"[E] Using a dot operator to access an individual bit is a language extension. ",
		3665:"Unnamed bit-field consisting of a single bit declared with a signed type. ",
		3670:"Recursive call to function containing this call. ",
		3671:"Function called via pointer to function. ",
		3672:"Using non-const pointer to function. ",
		3673:"The object addressed by the pointer parameter '%s' is not modified and so the pointer could be of ty",
		3674:"Array size defined implicitly with an initaliser. ",
		3675:"Function parameter declared with type qualification which differs from previous declaration. ",
		3680:"[U] Indexing array with constant value that is out of bounds. ",
		3681:"Pointer index constant is negative. ",
		3682:"Index may take a value greater than number of elements. ",
		3683:"Array index constant addresses the location one beyond the end of the array. ",
		3684:"Array declared with unknown size. ",
		3685:"[U] Indexing array with value that will definitely be out of bounds. ",
		3686:"Pointer index value is definitely negative. ",
		3688:"Array index value definitely addresses the location one beyond the end of the array. ",
		3689:"[U] Indexing array with value that will apparently be out of bounds. ",
		3690:"Pointer index value is apparently negative. ",
		3692:"Array index value apparently addresses the location one beyond the end of the array. ",
		3700:"Implicit conversion: char to signed char. ",
		3701:"Implicit conversion: char to unsigned char. ",
		3702:"Implicit conversion: char to short. ",
		3703:"Implicit conversion: char to unsigned short. ",
		3704:"Implicit conversion: char to int. ",
		3705:"Implicit conversion: char to unsigned int. ",
		3706:"Implicit conversion: char to long. ",
		3707:"Implicit conversion: char to unsigned long. ",
		3708:"Implicit conversion: char to float. ",
		3709:"Implicit conversion: char to double. ",
		3710:"Implicit conversion: char to long double. ",
		3711:"Implicit conversion: unsigned char to char. ",
		3712:"Implicit conversion: unsigned char to signed char. ",
		3713:"Implicit conversion: unsigned char to short. ",
		3715:"Implicit conversion: unsigned char to int. ",
		3717:"Implicit conversion: unsigned char to long. ",
		3719:"Implicit conversion: unsigned char to float. ",
		3720:"Implicit conversion: unsigned char to double. ",
		3721:"Implicit conversion: unsigned char to long double. ",
		3722:"Implicit conversion: signed char to char. ",
		3723:"Implicit conversion: signed char to unsigned char. ",
		3725:"Implicit conversion: signed char to unsigned short. ",
		3727:"Implicit conversion: signed char to unsigned int. ",
		3729:"Implicit conversion: signed char to unsigned long. ",
		3730:"Implicit conversion: signed char to float. ",
		3731:"Implicit conversion: signed char to double. ",
		3732:"Implicit conversion: signed char to long double. ",
		3733:"Implicit conversion: short to char. ",
		3734:"Implicit conversion: short to signed char. ",
		3735:"Implicit conversion: short to unsigned char. ",
		3736:"Implicit conversion: short to unsigned short. ",
		3738:"Implicit conversion: short to unsigned int. ",
		3740:"Implicit conversion: short to unsigned long. ",
		3741:"Implicit conversion: short to float. ",
		3742:"Implicit conversion: short to double. ",
		3743:"Implicit conversion: short to long double. ",
		3744:"Implicit conversion: unsigned short to char. ",
		3745:"Implicit conversion: unsigned short to signed char. ",
		3746:"Implicit conversion: unsigned short to unsigned char. ",
		3747:"Implicit conversion: unsigned short to short. ",
		3748:"Implicit conversion: unsigned short to int. ",
		3750:"Implicit conversion: unsigned short to long. ",
		3752:"Implicit conversion: unsigned short to float. ",
		3753:"Implicit conversion: unsigned short to double. ",
		3754:"Implicit conversion: unsigned short to long double. ",
		3755:"Implicit conversion: int to char. ",
		3756:"Implicit conversion: int to signed char. ",
		3757:"Implicit conversion: int to unsigned char. ",
		3758:"Implicit conversion: int to short. ",
		3759:"Implicit conversion: int to unsigned short. ",
		3760:"Implicit conversion: int to unsigned int. ",
		3762:"Implicit conversion: int to unsigned long. ",
		3763:"Implicit conversion: int to float. ",
		3764:"Implicit conversion: int to double. ",
		3765:"Implicit conversion: int to long double. ",
		3766:"Implicit conversion: unsigned int to char. ",
		3767:"Implicit conversion: unsigned int to signed char. ",
		3768:"Implicit conversion: unsigned int to unsigned char. ",
		3769:"Implicit conversion: unsigned int to short. ",
		3770:"Implicit conversion: unsigned int to unsigned short. ",
		3771:"Implicit conversion: unsigned int to int. ",
		3772:"Implicit conversion: unsigned int to long. ",
		3774:"Implicit conversion: unsigned int to float. ",
		3775:"Implicit conversion: unsigned int to double. ",
		3776:"Implicit conversion: unsigned int to long double. ",
		3777:"Implicit conversion: long to char. ",
		3778:"Implicit conversion: long to signed char. ",
		3779:"Implicit conversion: long to unsigned char. ",
		3780:"Implicit conversion: long to short. ",
		3781:"Implicit conversion: long to unsigned short. ",
		3782:"Implicit conversion: long to int. ",
		3783:"Implicit conversion: long to unsigned int. ",
		3784:"Implicit conversion: long to unsigned long. ",
		3785:"Implicit conversion: long to float. ",
		3786:"Implicit conversion: long to double. ",
		3787:"Implicit conversion: long to long double. ",
		3788:"Implicit conversion: unsigned long to char. ",
		3789:"Implicit conversion: unsigned long to signed char. ",
		3790:"Implicit conversion: unsigned long to unsigned char. ",
		3791:"Implicit conversion: unsigned long to short. ",
		3792:"Implicit conversion: unsigned long to unsigned short. ",
		3793:"Implicit conversion: unsigned long to int. ",
		3794:"Implicit conversion: unsigned long to unsigned int. ",
		3795:"Implicit conversion: unsigned long to long. ",
		3796:"Implicit conversion: unsigned long to float. ",
		3797:"Implicit conversion: unsigned long to double. ",
		3798:"Implicit conversion: unsigned long to long double. ",
		3799:"Implicit conversion: float to char. ",
		3800:"Implicit conversion: float to signed char. ",
		3801:"Implicit conversion: float to unsigned char. ",
		3802:"Implicit conversion: float to short. ",
		3803:"Implicit conversion: float to unsigned short. ",
		3804:"Implicit conversion: float to int. ",
		3805:"Implicit conversion: float to unsigned int. ",
		3806:"Implicit conversion: float to long. ",
		3807:"Implicit conversion: float to unsigned long. ",
		3810:"Implicit conversion: double to char. ",
		3811:"Implicit conversion: double to signed char. ",
		3812:"Implicit conversion: double to unsigned char. ",
		3813:"Implicit conversion: double to short. ",
		3814:"Implicit conversion: double to unsigned short. ",
		3815:"Implicit conversion: double to int. ",
		3816:"Implicit conversion: double to unsigned int. ",
		3817:"Implicit conversion: double to long. ",
		3818:"Implicit conversion: double to unsigned long. ",
		3819:"Implicit conversion: double to float. ",
		3821:"Implicit conversion: long double to char. ",
		3822:"Implicit conversion: long double to signed char. ",
		3823:"Implicit conversion: long double to unsigned char. ",
		3824:"Implicit conversion: long double to short. ",
		3825:"Implicit conversion: long double to unsigned short . ",
		3826:"Implicit conversion: long double to int. ",
		3827:"Implicit conversion: long double to unsigned int. ",
		3828:"Implicit conversion: long double to long. ",
		3829:"Implicit conversion: long double to unsigned long. ",
		3830:"Implicit conversion: long double to float. ",
		3831:"Implicit conversion: long double to double. ",
		3832:"Implicit conversion: char to long long. ",
		3833:"Implicit conversion: char to unsigned long long. ",
		3834:"Implicit conversion: unsigned char to long long. ",
		3837:"Implicit conversion: signed char to unsigned long long. ",
		3839:"Implicit conversion: short to unsigned long long. ",
		3840:"Implicit conversion: unsigned short to long long. ",
		3843:"Implicit conversion: int to unsigned long long. ",
		3844:"Implicit conversion: unsigned int to long long. ",
		3847:"Implicit conversion: long to unsigned long long. ",
		3848:"Implicit conversion: unsigned long to long long. ",
		3850:"Implicit conversion: long long to char. ",
		3851:"Implicit conversion: long long to signed char. ",
		3852:"Implicit conversion: long long to unsigned char. ",
		3853:"Implicit conversion: long long to short. ",
		3854:"Implicit conversion: long long to unsigned short. ",
		3855:"Implicit conversion: long long to int. ",
		3856:"Implicit conversion: long long to unsigned int. ",
		3857:"Implicit conversion: long long to long ",
		3858:"Implicit conversion: long long to unsigned long. ",
		3859:"Implicit conversion: long long to unsigned long long. ",
		3860:"Implicit conversion: long long to float. ",
		3861:"Implicit conversion: long long to double. ",
		3862:"Implicit conversion: long long to long double. ",
		3863:"Implicit conversion: unsigned long long to char. ",
		3864:"Implicit conversion: unsigned long long to signed char. ",
		3865:"Implicit conversion: unsigned long long to unsigned char. ",
		3866:"Implicit conversion: unsigned long long to short. ",
		3867:"Implicit conversion: unsigned long long to unsigned short. ",
		3868:"Implicit conversion: unsigned long long to int. ",
		3869:"Implicit conversion: unsigned long long to unsigned int. ",
		3870:"Implicit conversion: unsigned long long to long. ",
		3871:"Implicit conversion: unsigned long long to unsigned long. ",
		3872:"Implicit conversion: unsigned long long to long long. ",
		3873:"Implicit conversion: unsigned long long to float. ",
		3874:"Implicit conversion: unsigned long long to double. ",
		3875:"Implicit conversion: unsigned long long to long double. ",
		3876:"Implicit conversion: float to long long. ",
		3877:"Implicit conversion: float to unsigned long long. ",
		3878:"Implicit conversion: double to long long. ",
		3879:"Implicit conversion: double to unsigned long long. ",
		3880:"Implicit conversion: long double to long long. ",
		3881:"Implicit conversion: long double to unsigned long long. ",
		3892:"The result of this cast is implicitly converted to another type. ",
		3900:"char value returned from signed char %s(). ",
		3901:"char value returned from unsigned char %s(). ",
		3902:"char value returned from short %s(). ",
		3903:"char value returned from unsigned short %s(). ",
		3904:"char value returned from int %s(). ",
		3905:"char value returned from unsigned int %s(). ",
		3906:"char value returned from long %s(). ",
		3907:"char value returned from unsigned long %s(). ",
		3908:"char value returned from float %s(). ",
		3909:"char value returned from double %s(). ",
		3910:"char value returned from long double %s(). ",
		3911:"unsigned char value returned from char %s(). ",
		3912:"unsigned char value returned from signed char %s(). ",
		3913:"unsigned char value returned from short %s(). ",
		3915:"unsigned char value returned from int %s(). ",
		3917:"unsigned char value returned from long %s(). ",
		3919:"unsigned char value returned from float %s(). ",
		3920:"unsigned char value returned from double %s(). ",
		3921:"unsigned char value returned from long double %s(). ",
		3922:"signed char value returned from char %s(). ",
		3923:"signed char value returned from unsigned char %s(). ",
		3925:"signed char value returned from unsigned short %s(). ",
		3927:"signed char value returned from unsigned int %s(). ",
		3929:"signed char value returned from unsigned long %s(). ",
		3930:"signed char value returned from float %s(). ",
		3931:"signed char value returned from double %s(). ",
		3932:"signed char value returned from long double %s(). ",
		3933:"short value returned from char %s(). ",
		3934:"short value returned from signed char %s(). ",
		3935:"short value returned from unsigned char %s(). ",
		3936:"short value returned from unsigned short %s(). ",
		3938:"short value returned from unsigned int %s(). ",
		3940:"short value returned from unsigned long %s(). ",
		3941:"short value returned from float %s(). ",
		3942:"short value returned from double %s(). ",
		3943:"short value returned from long double %s(). ",
		3944:"unsigned short value returned from char %s(). ",
		3945:"unsigned short value returned from signed char %s(). ",
		3946:"unsigned short value returned from unsigned char %s(). ",
		3947:"unsigned short value returned from short %s(). ",
		3948:"unsigned short value returned from int %s(). ",
		3950:"unsigned short value returned from long %s(). ",
		3952:"unsigned short value returned from float %s(). ",
		3953:"unsigned short value returned from double %s(). ",
		3954:"unsigned short value returned from long double %s(). ",
		3955:"int value returned from char %s(). ",
		3956:"int value returned from signed char %s(). ",
		3957:"int value returned from unsigned char %s(). ",
		3958:"int value returned from short %s(). ",
		3959:"int value returned from unsigned short %s(). ",
		3960:"int value returned from unsigned int %s(). ",
		3962:"int value returned from unsigned long %s(). ",
		3963:"int value returned from float %s(). ",
		3964:"int value returned from double %s(). ",
		3965:"int value returned from long double %s(). ",
		3966:"unsigned int value returned from char %s(). ",
		3967:"unsigned int value returned from signed char %s(). ",
		3968:"unsigned int value returned from unsigned char %s(). ",
		3969:"unsigned int value returned from short %s(). ",
		3970:"unsigned int value returned from unsigned short %s(). ",
		3971:"unsigned int value returned from int %s(). ",
		3972:"unsigned int value returned from long %s(). ",
		3974:"unsigned int value returned from float %s(). ",
		3975:"unsigned int value returned from double %s(). ",
		3976:"unsigned int value returned from long double %s(). ",
		3977:"long value returned from char %s(). ",
		3978:"long value returned from signed char %s(). ",
		3979:"long value returned from unsigned char %s(). ",
		3980:"long value returned from short %s(). ",
		3981:"long value returned from unsigned short %s(). ",
		3982:"long value returned from int %s(). ",
		3983:"long value returned from unsigned int %s(). ",
		3984:"long value returned from unsigned long %s(). ",
		3985:"long value returned from float %s(). ",
		3986:"long value returned from double %s(). ",
		3987:"long value returned from long double %s(). ",
		3988:"unsigned long value returned from char %s(). ",
		3989:"unsigned long value returned from signed char %s(). ",
		3990:"unsigned long value returned from unsigned char %s(). ",
		3991:"unsigned long value returned from short %s(). ",
		3992:"unsigned long value returned from unsigned short %s(). ",
		3993:"unsigned long value returned from int %s(). ",
		3994:"unsigned long value returned from unsigned int %s(). ",
		3995:"unsigned long value returned from long %s(). ",
		3996:"unsigned long value returned from float %s(). ",
		3997:"unsigned long value returned from double %s(). ",
		3998:"unsigned long value returned from long double %s(). ",
		3999:"float value returned from char %s(). ",
		4000:"float value returned from signed char %s(). ",
		4001:"float value returned from unsigned char %s(). ",
		4002:"float value returned from short %s(). ",
		4003:"float value returned from unsigned short %s(). ",
		4004:"float value returned from int %s(). ",
		4005:"float value returned from unsigned int %s(). ",
		4006:"float value returned from long %s(). ",
		4007:"float value returned from unsigned long %s(). ",
		4010:"double value returned from char %s(). ",
		4011:"double value returned from signed char %s(). ",
		4012:"double value returned from unsigned char %s(). ",
		4013:"double value returned from short %s(). ",
		4014:"double value returned from unsigned short %s(). ",
		4015:"double value returned from int %s(). ",
		4016:"double value returned from unsigned int %s(). ",
		4017:"double value returned from long %s(). ",
		4018:"double value returned from unsigned long %s(). ",
		4019:"double value returned from float %s(). ",
		4021:"long double value returned from char %s(). ",
		4022:"long double value returned from signed char %s(). ",
		4023:"long double value returned from unsigned char %s(). ",
		4024:"long double value returned from short %s(). ",
		4025:"long double value returned from unsigned short %s(). ",
		4026:"long double value returned from int %s(). ",
		4027:"long double value returned from unsigned int %s(). ",
		4028:"long double value returned from long %s(). ",
		4029:"long double value returned from unsigned long %s(). ",
		4030:"long double value returned from float %s(). ",
		4031:"long double value returned from double %s(). ",
		4032:"char value returned from long long %s(). ",
		4033:"char value returned from unsigned long long %s(). ",
		4034:"unsigned char value returned from long long %s(). ",
		4037:"signed char value returned from unsigned long long %s(). ",
		4039:"short value returned from unsigned long long %s(). ",
		4040:"unsigned short value returned from long long %s(). ",
		4043:"int value returned from unsigned long long %s(). ",
		4044:"unsigned int value returned from long long %s(). ",
		4047:"long value returned from unsigned long long %s(). ",
		4048:"unsigned long value returned from long long %s(). ",
		4050:"long long value returned from char %s(). ",
		4051:"long long value returned from signed char %s(). ",
		4052:"long long value returned from unsigned char %s(). ",
		4053:"long long value returned from short %s(). ",
		4054:"long long value returned from unsigned short %s(). ",
		4055:"long long value returned from int %s(). ",
		4056:"long long value returned from unsigned int %s(). ",
		4057:"long long value returned from long %s(). ",
		4058:"long long value returned from unsigned long %s(). ",
		4059:"long long value returned from unsigned long long %s(). ",
		4060:"long long value returned from float %s(). ",
		4061:"long long value returned from double %s(). ",
		4062:"long long value returned from long double %s(). ",
		4063:"unsigned long long value returned from char %s(). ",
		4064:"unsigned long long value returned from signed char %s(). ",
		4065:"unsigned long long value returned from unsigned char %s(). ",
		4066:"unsigned long long value returned from short %s(). ",
		4067:"unsigned long long value returned from unsigned short %s(). ",
		4068:"unsigned long long value returned from int %s(). ",
		4069:"unsigned long long value returned from unsigned int %s(). ",
		4070:"unsigned long long value returned from long %s(). ",
		4071:"unsigned long long value returned from unsigned long %s(). ",
		4072:"unsigned long long value returned from long long %s(). ",
		4073:"unsigned long long value returned from float %s(). ",
		4074:"unsigned long long value returned from double %s(). ",
		4075:"unsigned long long value returned from long double %s(). ",
		4076:"float value returned from long long %s(). ",
		4077:"float value returned from unsigned long long %s(). ",
		4078:"double value returned from long long %s(). ",
		4079:"double value returned from unsigned long long %s(). ",
		4080:"long double value returned from long long %s(). ",
		4081:"long double value returned from unsigned long long %s(). ",
		4100:"Illegal user error number msg ",
		4101:"Both operands of & operator are 'boolean' expressions. ",
		4102:"Both operands of | operator are 'boolean' expressions. ",
		4103:"Both operands of arithmetic or bitwise operator are 'boolean' expressions. ",
		4104:"Left hand operand of arithmetic or bitwise operator is a 'boolean' expression. ",
		4105:"Right hand operand of arithmetic or bitwise operator is a 'boolean' expression. ",
		4106:"Both operands of && operator are arithmetic or bitwise expressions. ",
		4107:"Both operands of || operator are arithmetic or bitwise expressions. ",
		4108:"Left hand operand of logical operator is an arithmetic or bitwise expression. ",
		4109:"Right hand operand of logical operator is an arithmetic or bitwise expression. ",
		4110:"Operand of ! operator is an arithmetic or bitwise expression. ",
		4111:"Right hand operand of relational operator is a 'boolean' expression. ",
		4112:"Left hand operand of relational operator is a 'boolean' expression. ",
		4113:"Both operands of relational operator are 'boolean' expressions. ",
		4114:"Operand of ~ operator is a 'boolean' expression. ",
		4117:"The result of an integer division operation is being implicitly converted to a floating type. ",
		4118:"The result of an integer division operation is being cast to a floating type. ",
		4119:"Cast of floating point expression to an integral type. Make sure that any necessary rounding has bee",
		4120:"Implicit conversion: complex expression of integral type to wider type. ",
		4121:"Cast of complex expression of integral type to wider type. ",
		4123:"Implicit conversion: complex expression of type float to type double. ",
		4124:"Implicit conversion: complex expression of type float to type long double. ",
		4125:"Implicit conversion: complex expression of type double to type long double. ",
		4126:"Cast of complex expression of type float to type double. ",
		4127:"Cast of complex expression of type float to type long double. ",
		4128:"Cast of complex expression of type double to type long double. ",
		4130:"Bitwise operations on signed data will give implementation defined results. ",
		4131:"Left shift operation on signed operand. ",
		4139:"Function returns address of local static data. ",
		4140:"Function returns address of automatic data. ",
		4150:"The name '%s' may cause confusion because it contains only the characters 'l' and '1'. ",
		4151:"The name '%s' may cause confusion because it contains only the characters '0' and 'O'. ",
		4152:"The name '%s' may cause confusion because it contains both the characters 'l' and '1'. ",
		4153:"The name '%s' may cause confusion because it contains both the characters 'O' and '0'. ",
		4700:"Metric value out of threshold range: %s. ",
		4800:"The identifier 'name' does not conform to the name rule ",
		4810:"Invalid annotation: tag 'locTag' is not defined subsequently in this file. ",
		4811:"The start of the range 'locTag', starts and ends at the same location. ",
		4812:"'tag' not allowed here. ",
		4820:"Annotation kind is expected. ",
		4821:"Colon is expected. ",
		4822:"Tag name is expected. ",
		4823:"Annotation syntax error. ",
		4824:"Invalid character in tag name. ",
		4825:"Unexpected character. ",
		4826:"Message specification is incomplete or missing. ",
		4827:"Tag name is not allowed in the message specification of continuous suppression annotation. ",
		4828:"Invalid usage of predefined location tag. "
	}
